---
- total_users:
    description: "Total users"
    model: User
    datetime_attr: created_at
    group_by: state
    group_by_values_map: <%= ModelsStats.convert_hash_to_yaml({0 => 'new', 1 => 'ok'}) %>
    graphic_lib: metrics_graphics
    graphic_type: stacked
    graph_width: 1500
    graph_height: 200
    date_format: '%d/%m'
    date_tick: month
- total_comments:
    description: "Total comments"
    model: Comment
- total_profiles:
    description: "Total profiles"
    model: Profile
    graphic_type: stack
